// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   AboutViewModel.tt
using System.CodeDom.Compiler;
using System.Runtime.CompilerServices;
using System.Windows.Input;
using ViewModelsBase=WPAppStudio.ViewModel.Base;
using WPAppStudio;
using WPAppStudio.Entities.Base;
using WPAppStudio.Services.Interfaces;
using WPAppStudio.ViewModel.Base;
using WPAppStudio.ViewModel.Interfaces;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of About ViewModel.
    /// </summary>
    public partial class AboutViewModel : ViewModelsBase.VMBase, IAboutViewModel
    {       
		private string _title;
		private string _description;
		private string _version;
		private string _appLink;
		private readonly INavigationService _navigationService;
		private readonly IShareService _shareService;
		
		public string Title 
		{ 
			get 
			{ 
				return _title; 
			} 
			set
			{
				SetProperty(ref _title, value);
			}			
		}
		
		public string Description 
		{ 
			get 
			{ 
				return _description; 
			} 
			set
			{
				SetProperty(ref _description, value);
			}			
		}

		public string Version 
		{ 
			get 
			{ 
				return _version; 
			} 
			set
			{
				SetProperty(ref _version, value);
			}			
		}

		public string AppLink
        {
            get
            {
                return _appLink;
            }
            set
            {
                SetProperty(ref _appLink, value);
            }
        }
				
        /// <summary>
        /// Initializes a new instance of the <see cref="AboutViewModel" /> class.
        /// </summary>
        public AboutViewModel(INavigationService navigationService, IShareService shareService)
        {
			_title = @"Puri";
			_description = @"This app shows the virtues of holy city ""Puri"" which is situated in Odisha, India. It features in trying to show/depict the culture, monuments, people of this small but popular city well known for the Car-Festival (Rath-Yatra)."; 
			_version = "v1";
			_appLink = "https://apps.windowsstore.com/DashBoard/DownloadAppXap?appId=6db54d9f-884f-4583-b7d7-c78d46374d22";
			_navigationService = navigationService;
			_shareService = shareService;
        }
		
		private ICommand _licenseCommand;

        /// <summary>
        /// Gets the LicenseCommand command.
        /// </summary>
        public ICommand LicenseCommand
        {
            get { return _licenseCommand = _licenseCommand ?? new DelegateCommand(LicenseCommandDelegate); }
        }

        public void LicenseCommandDelegate()
        {
            _navigationService.NavigateTo<ILicenseViewModel>();
        }

		/// <summary>
        /// Delegate method for the ShareAppCommand command.
        /// </summary>
        public void ShareAppCommandDelegate()
        {
            if (_shareService.AppExistInMarketPlace())
            {
                AppLink = Windows.ApplicationModel.Store.CurrentApp.LinkUri.AbsoluteUri;
            }
            _shareService.Share(Title, Description, AppLink);
        }

        private ICommand _shareAppCommand;

        /// <summary>
        /// Gets the ShareAppCommand command.
        /// </summary>
        public ICommand ShareAppCommand
        {
            get { return _shareAppCommand = _shareAppCommand ?? new DelegateCommand(ShareAppCommandDelegate); }
        }
    }
}
