// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ViewModel.tt
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Controls=WPAppStudio.Controls;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;
using IServices=WPAppStudio.Services.Interfaces;
using IViewModels=WPAppStudio.ViewModel.Interfaces;
using Localization=WPAppStudio.Localization;
using Repositories=WPAppStudio.Repositories;
using Services=WPAppStudio.Services;
using ViewModelsBase=WPAppStudio.ViewModel.Base;
using WPAppStudio;
using WPAppStudio.Shared;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of monuments_Detail ViewModel.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public partial class monuments_DetailViewModel : ViewModelsBase.VMBase, IViewModels.Imonuments_DetailViewModel, ViewModelsBase.INavigable
    {       

		private readonly IServices.IDialogService _dialogService;
		private readonly IServices.INavigationService _navigationService;
		private readonly IServices.ISpeechService _speechService;
		private readonly IServices.IShareService _shareService;
		private readonly IServices.ILiveTileService _liveTileService;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="monuments_DetailViewModel" /> class.
        /// </summary>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="speechService">The Speech Service.</param>
        /// <param name="shareService">The Share Service.</param>
        /// <param name="liveTileService">The Live Tile Service.</param>
        public monuments_DetailViewModel(IServices.IDialogService dialogService, IServices.INavigationService navigationService, IServices.ISpeechService speechService, IServices.IShareService shareService, IServices.ILiveTileService liveTileService)
        {
			_dialogService = dialogService;
			_navigationService = navigationService;
			_speechService = speechService;
			_shareService = shareService;
			_liveTileService = liveTileService;
        }
		
	
		private Entities.monumentsCollectionSchema _currentmonumentsCollectionSchema;

        /// <summary>
        /// CurrentmonumentsCollectionSchema property.
        /// </summary>		
        public Entities.monumentsCollectionSchema CurrentmonumentsCollectionSchema
        {
            get
            {
				return _currentmonumentsCollectionSchema;
            }
            set
            {
                SetProperty(ref _currentmonumentsCollectionSchema, value);
            }
        }

        /// <summary>
        /// Delegate method for the TextToSpeechmonuments_DetailStaticControlCommand command.
        /// </summary>
        public  void TextToSpeechmonuments_DetailStaticControlCommandDelegate() 
        {
				_speechService.TextToSpeech(CurrentmonumentsCollectionSchema.Subtitle);
        }
		

        private ICommand _textToSpeechmonuments_DetailStaticControlCommand;

        /// <summary>
        /// Gets the TextToSpeechmonuments_DetailStaticControlCommand command.
        /// </summary>
        public ICommand TextToSpeechmonuments_DetailStaticControlCommand
        {
            get { return _textToSpeechmonuments_DetailStaticControlCommand = _textToSpeechmonuments_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(TextToSpeechmonuments_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the Sharemonuments_DetailStaticControlCommand command.
        /// </summary>
        public  void Sharemonuments_DetailStaticControlCommandDelegate() 
        {
				_shareService.Share(CurrentmonumentsCollectionSchema.Subtitle, "", "", CurrentmonumentsCollectionSchema.Image);
        }
		

        private ICommand _sharemonuments_DetailStaticControlCommand;

        /// <summary>
        /// Gets the Sharemonuments_DetailStaticControlCommand command.
        /// </summary>
        public ICommand Sharemonuments_DetailStaticControlCommand
        {
            get { return _sharemonuments_DetailStaticControlCommand = _sharemonuments_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(Sharemonuments_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the PinToStartmonuments_DetailStaticControlCommand command.
        /// </summary>
        public  void PinToStartmonuments_DetailStaticControlCommandDelegate() 
        {
				_liveTileService.PinToStart(typeof(IViewModels.Imonuments_DetailViewModel), CreateTileInfomonuments_DetailStaticControl());
        }
		

        private ICommand _pinToStartmonuments_DetailStaticControlCommand;

        /// <summary>
        /// Gets the PinToStartmonuments_DetailStaticControlCommand command.
        /// </summary>
        public ICommand PinToStartmonuments_DetailStaticControlCommand
        {
            get { return _pinToStartmonuments_DetailStaticControlCommand = _pinToStartmonuments_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(PinToStartmonuments_DetailStaticControlCommandDelegate); }
        }
		public object NavigationContext
        {
            set
            {              
                if (!(value is Entities.monumentsCollectionSchema)) { return; }
                
                CurrentmonumentsCollectionSchema = value as Entities.monumentsCollectionSchema;
            }
        }
        /// <summary>
        /// Initializes a <see cref="Services.TileInfo" /> object for the monuments_DetailStaticControl control.
        /// </summary>
		/// <returns>A <see cref="Services.TileInfo" /> object.</returns>
        public Services.TileInfo CreateTileInfomonuments_DetailStaticControl()
        {
            var tileInfo = new Services.TileInfo
            {
                CurrentId = CurrentmonumentsCollectionSchema.Id.ToString(),
                Title = CurrentmonumentsCollectionSchema.Subtitle,
                BackTitle = CurrentmonumentsCollectionSchema.Subtitle,
                BackContent = string.Empty,
                Count = 0,
                BackgroundImagePath = CurrentmonumentsCollectionSchema.Image,
                BackBackgroundImagePath = CurrentmonumentsCollectionSchema.Image,
                LogoPath = "Logo-aafb5c9d-c352-45d2-8a05-ca75f71cb409.png"
            };
            return tileInfo;
        }
        /// <summary>
        /// Initializes a <see cref="Services.TileInfo" /> object for the AboutThisPlaceStaticControl control.
        /// </summary>
		/// <returns>A <see cref="Services.TileInfo" /> object.</returns>
        public Services.TileInfo CreateTileInfoAboutThisPlaceStaticControl()
        {
            var tileInfo = new Services.TileInfo
            {
                CurrentId = CurrentmonumentsCollectionSchema.Id.ToString(),
                Title = CurrentmonumentsCollectionSchema.Title,
                BackTitle = CurrentmonumentsCollectionSchema.Title,
                BackContent = CurrentmonumentsCollectionSchema.Description,
                Count = 0,
                BackgroundImagePath = string.Empty,
                BackBackgroundImagePath = string.Empty,
                LogoPath = "Logo-aafb5c9d-c352-45d2-8a05-ca75f71cb409.png"
            };
            return tileInfo;
        }
    }
}
