// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// info_Info ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface Iinfo_InfoViewModel
    {		
	    /// <summary>
        /// IsInternetAvalaible property.
        /// </summary>		
        Visibility IsInternetAvalaible { get; }
        /// <summary>
        /// Gets/Sets the Currentinfo_InfoHtmlControl property.
        /// </summary>
		string Currentinfo_InfoHtmlControl { get; set; }
        /// <summary>
        /// Gets/Sets the Monuments_ListListControlCollection property.
        /// </summary>
		ObservableCollection<Entities.monumentsCollectionSchema> Monuments_ListListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the Monuments_ListListControlCollectionPageNumber property.
        /// </summary>
		int Monuments_ListListControlCollectionPageNumber { get; set; }
        /// <summary>
        /// Gets/Sets the Selectedmonuments_ListListControlCollection property.
        /// </summary>
		Entities.monumentsCollectionSchema Selectedmonuments_ListListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the SpecialPlaces_ListListControlCollection property.
        /// </summary>
		ObservableCollection<Entities.specialplacesCollectionSchema> SpecialPlaces_ListListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the SpecialPlaces_ListListControlCollectionPageNumber property.
        /// </summary>
		int SpecialPlaces_ListListControlCollectionPageNumber { get; set; }
        /// <summary>
        /// Gets/Sets the SelectedSpecialPlaces_ListListControlCollection property.
        /// </summary>
		Entities.specialplacesCollectionSchema SelectedSpecialPlaces_ListListControlCollection { get; set; }
        
        /// <summary>
        /// Gets the Getmonuments_ListListControlCollectionCommand command.
        /// </summary>
		ICommand Getmonuments_ListListControlCollectionCommand { get; }

        
        /// <summary>
        /// Gets the GetSpecialPlaces_ListListControlCollectionCommand command.
        /// </summary>
		ICommand GetSpecialPlaces_ListListControlCollectionCommand { get; }

        
        /// <summary>
        /// Gets the TextToSpeechinfo_InfoHtmlControlCommand command.
        /// </summary>
		ICommand TextToSpeechinfo_InfoHtmlControlCommand { get; }

        
        /// <summary>
        /// Gets the Shareinfo_InfoHtmlControlCommand command.
        /// </summary>
		ICommand Shareinfo_InfoHtmlControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartinfo_InfoHtmlControlCommand command.
        /// </summary>
		ICommand PinToStartinfo_InfoHtmlControlCommand { get; }

        
        /// <summary>
        /// Gets the SetLockScreenCommand command.
        /// </summary>
		ICommand SetLockScreenCommand { get; }

        
        /// <summary>
        /// Gets the AboutCommand command.
        /// </summary>
		ICommand AboutCommand { get; }

	}
}
