// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// monuments_Detail ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface Imonuments_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentmonumentsCollectionSchema property.
        /// </summary>
		Entities.monumentsCollectionSchema CurrentmonumentsCollectionSchema { get; set; }
        
        /// <summary>
        /// Gets the TextToSpeechmonuments_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechmonuments_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the Sharemonuments_DetailStaticControlCommand command.
        /// </summary>
		ICommand Sharemonuments_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartmonuments_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartmonuments_DetailStaticControlCommand { get; }

	}
}
