// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IDataSource.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// monuments_monumentsCollection interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface Imonuments_monumentsCollection
    {
		ObservableCollection<Entities.monumentsCollectionSchema> GetData(int pageNumber = 0);
		ObservableCollection<Entities.monumentsCollectionSchema> Search(FilterSpecification filter);
		bool HasPrevious(Entities.monumentsCollectionSchema current);
		bool HasNext(Entities.monumentsCollectionSchema current);
		Entities.monumentsCollectionSchema Previous(Entities.monumentsCollectionSchema current);
		Entities.monumentsCollectionSchema Next(Entities.monumentsCollectionSchema current);
    }
}
