// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   DataSource.tt
using System;
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using System.Runtime.CompilerServices;
using Entities=WPAppStudio.Entities;
using RepositoriesBase=WPAppStudio.Repositories.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// info_Html data source.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public class info_info : Iinfo_info 
    {        
        /// <summary>
        /// Retrieves the html content.
        /// </summary>
        /// <returns>A string with the content in html format.</returns>
        public string Get()
        {			
            return @"<p><b>Puri (ପୁରୀ) is a city and the district headquarters of Puri district, Odisha, eastern India. It is situated on the Bay of Bengal, 60 kilometres (37 mi) south of the state capital of Bhubaneswar. It is also known as Jagannath Puri after the 11th century Jagannath Temple located in the city. It is a holy city of the Hindus as a part of the original Char Dham pilgrimages, of which the other legs are Dwaraka,Badrinath and Rameswaram. According to Hindu teachings, a pilgrimage of the temples of India is not considered complete without a journey to Puri.</b><b>Puri Beach is a popular beach resort. Sun Temple Konark is at distance of around 35 km from Puri.<i /></b><i><b /></i></p>";
        }
	}
}

