// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   DataSource.tt
using System;
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using System.Runtime.CompilerServices;
using Entities=WPAppStudio.Entities;
using RepositoriesBase=WPAppStudio.Repositories.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// monuments_monumentsCollection data source.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public class monuments_monumentsCollection : Imonuments_monumentsCollection 
    {
		private const int MaxResults = 10;
        private readonly ObservableCollection<Entities.monumentsCollectionSchema> _data = new ObservableCollection<Entities.monumentsCollectionSchema>
		{
          new Entities.monumentsCollectionSchema
            {
                Id= new Guid("f68248da-6eb6-4c3b-a9be-b2b024f77364"),
                Title=@"Bhoga Mandap",
                Subtitle=@"Bhoga Mandap or Food Mandap is situated near the Jagannath Temple in Puri.",
                Image=@"\Images\Item-34c0d2fc-7772-41a1-bf0d-abaf3b2d66ef.jpg",
                Description=@"Bhoga Mandap or Food Mandap is situated near the Jagannath Temple in Puri. It was constructed by a king of the region to feed a large number of pilgrims who assembled here to have a darshan of Lord Jagannath. For the preparation of such Bhoga (food), he also built a large kitchen in the temple premises. The constructions of these buildings are unique and they are still being used for the preparation of Bhoga and thousands of people take prasad every day from here.",
			},
          new Entities.monumentsCollectionSchema
            {
                Id= new Guid("13991ebe-f14d-49ca-b6d6-e5debbb4456d"),
                Title=@"Jagannath Temple",
                Subtitle=@"The Jagannath Temple in Puri is a famous Hindu temple dedicated to Jagannath and located in the coastal town of Puri in the state of Odisha, India.",
                Image=@"\Images\Item-f9999e02-41b8-4a8d-9d3b-3c5e1b8d1f25.jpg",
                Description=@"The name Jagannath (Lord of the Universe) is a combination of the Sanskrit words Jagat (Universe) and Nath (Lord of) and also, the word ""Jagannatha"" is evolved from ""Jagati""(as an elevated platform or ""Ratnabedi"" on which the wooden form of Jagannatha, Balabhadra and Subhadra are worshiped on or the temple or its precincts inside the ""Narendra Pokhari"") and ""Natha"".The temple is an important pilgrimage destination for many Hindu traditions, particularly worshippers of Krishna and Vishnu, and part of the Char Dham pilgrimages that a Hindu is expected to make in one's lifetime. The temple was built in the 11th century atop its ruins by the progenitor of the Eastern Ganga dynasty, King Anantavarman Chodaganga Deva.The temple is famous for its annual Rath Yatra, or chariot festival, in which the three main temple deities are hauled on huge and elaborately decorated temple cars. Since medieval times, it is also associated with intense religious fervour.
The temple is sacred to the Vaishnava traditions and saint Ramananda who was closely associated with the temple. It is also of particular significance to the followers of the Gaudiya Vaishnavism whose founder, Chaitanya Mahaprabhu, was attracted to the deity, Jagannath, and lived in Puri for many years.",
			},
          new Entities.monumentsCollectionSchema
            {
                Id= new Guid("87dbb15f-9735-498b-9204-37343fcc9576"),
                Title=@"Lokanath Temple",
                Subtitle=@"Shivaratri, Mondays especially of the month of Vaishakha, Shraavana and Kartika.",
                Image=@"\Images\Item-c05f331f-dd9f-4c4e-80cb-845131ffc4a1.jpg",
                Description=@"Close to Jagannath temple lays the 11th century Lokanatha temple, dedicated to Lord Shiva. According to history the lingam in this temple was established by Lord Rama. The unique feature is that the shivalinga is always under water which substantiates the legend that Goddess Ganga flows through the top of the shivalinga as a stream. The festival that is celebrated with great fervor and pomp is the Saranti Somavar Fair while devotees believe that the shivalinga has powers to cure diseases after seeking the darshan of Lord Shiva. The utsava murti of Lokanatha is kept inside the Jagannath temple, Puri. He is the guardian deity of all the treasures and jewellery of Lord Jagannath.",
			},
		};
	
		
        /// <summary>
        /// Retrieves the data from a static data source, in an observable collection of monumentsCollectionSchema items.
        /// </summary>
        /// <returns>An observable collection of monumentsCollectionSchema items.</returns>
        public ObservableCollection<Entities.monumentsCollectionSchema> GetData(int numPage)
        {								
			return new ObservableCollection<Entities.monumentsCollectionSchema>(_data.Skip(MaxResults * numPage).Take(MaxResults));
        }
		
		/// <summary>
        /// Retrieves the data from a static data source, filtered by a filter specification, in an observable collection of monumentsCollectionSchema items.
        /// </summary>
		/// <param name="filter">Filter operation specification</param>
        /// <returns>An observable collection of monumentsCollectionSchema items.</returns>
        public ObservableCollection<Entities.monumentsCollectionSchema> Search(FilterSpecification filter)
        {
            return RepositoriesBase.Filter<Entities.monumentsCollectionSchema>.FilterCollection(filter, _data);
        }
		
		/// <summary>
        /// Checks if data source has a element before the passed as parameter
        /// </summary>
		/// <param name="current">Current element</param>
        /// <returns>True, if there is a previous element, false if there is not</returns>
		public bool HasPrevious(Entities.monumentsCollectionSchema current)
        {
            if (current == null || !_data.Any()) return false;

            return _data.IndexOf(current) > 0;
        }
		
		/// <summary>
        /// Checks if data source has a element after the passed as parameter
        /// </summary>
		/// <param name="current">Current element</param>
        /// <returns>True, if there is a next element, false if there is not</returns>
		public bool HasNext(Entities.monumentsCollectionSchema current)
        {
            if (current == null || !_data.Any()) return false;

            return _data.IndexOf(current) < _data.Count - 1;
        }
		
		/// <summary>
        /// Retrieves the previous element from source.
        /// </summary>
		/// <param name="current">Current element</param>
        /// <returns>The previous element from items, if it exists. Otherwise, returns null</returns>
        public Entities.monumentsCollectionSchema Previous(Entities.monumentsCollectionSchema current)
        {
            if (current == null || !_data.Any()) return null;

            if (_data.First().Equals(current)) return null;

            return _data[_data.IndexOf(current) - 1];
        }
		
		/// <summary>
        /// Retrieves the next element from source.
        /// </summary>
		/// <param name="current">Current element</param>
        /// <returns>The next element from items, if it exists. Otherwise, returns null</returns>
        public Entities.monumentsCollectionSchema Next(Entities.monumentsCollectionSchema current)
        {
            if (current == null || !_data.Any()) return null;

            if (_data.Last().Equals(current)) return null;

            return _data[_data.IndexOf(current) + 1];
        }
	}
}

