// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   DataSource.tt
using System;
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using System.Runtime.CompilerServices;
using Entities=WPAppStudio.Entities;
using RepositoriesBase=WPAppStudio.Repositories.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// SpecialPlaces_specialplacesCollection data source.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public class SpecialPlaces_specialplacesCollection : ISpecialPlaces_specialplacesCollection 
    {
		private const int MaxResults = 10;
        private readonly ObservableCollection<Entities.specialplacesCollectionSchema> _data = new ObservableCollection<Entities.specialplacesCollectionSchema>
		{
          new Entities.specialplacesCollectionSchema
            {
                Id= new Guid("da676f94-ebb8-4e47-a192-e5f669d1dc3d"),
                Title=@"Beleswar Beach",
                Subtitle=@"Situated 15 km from Puri in Orissa, Beleswar Beach is famous for its calm and shallow waters.",
                Image=@"\Images\Item-4956b4a7-d28c-4dae-85f8-358e54b5a1b5.jpg",
                Description=@"Situated 15 km from Puri in Orissa, Beleswar Beach is famous for its calm and shallow waters. It is quite long and wide, extending for miles and has been a favorite haunt for the tourists from far and near. Shaivite temple located here is another main attraction of the beach.",
			},
          new Entities.specialplacesCollectionSchema
            {
                Id= new Guid("107de217-1ec2-4007-9df2-322a750605e3"),
                Title=@"Chilika Lake",
                Subtitle=@"Chilka Lake (ଚିଲିକା ହ୍ରଦ) is a brackish water lagoon, spread over the Puri, Khurda and Ganjam districts of Odisha state on the east coast of India, at the mouth of the Daya River, flowing into the Bay of Bengal, covering an area of over 1,100 km. It is the largest coastal lagoon in India and the second largest lagoon in the World.",
                Image=@"\Images\Item-bc24224c-88e8-40d5-a573-61b7a6d65e98.jpg",
                Description=@"It is the largest wintering ground for migratory birds on the Indian sub-continent. The lake is home to a number of threatened species of plants and animals.
The lake is an ecosystem with large fishery resources. It sustains more than 150,000 fisher–folk living in 132 villages on the shore and islands.
The lagoon hosts over 160 species of birds in the peak migratory season. Birds from as far as the Caspian Sea, Lake Baikal, Aral Sea and other remote parts of Russia, Kirghiz steppes of Mongolia, Central and southeast Asia, Ladakh and Himalayas come here. These birds travel great distances; migratory birds probably follow much longer routes than the straight lines, possibly up to 12,000 km, to reach Chilika Lake.
In 1981, Chilika Lake was designated the first Indian wetland of international importance under the Ramsar Convention.
According to a survey, 45 percent of the birds are terrestrial in nature, 32 percent are waterfowl, and 23 percent are waders. The lagoon is also home to 14 types of raptors. Around 152 rare and endangered Irrawaddy Dolphins have also been reported. Plus, the lagoon supports about 37 species of reptiles and amphibians.
The highly productive chilika lagoon ecosystem with its rich fishery resources sustains the livelihood for many fisher men who live in and near the Lagoon. The water spread area of the Lagoon ranges between 1165 to 906 km during the monsoon and summer respectively. A 32 km long, narrow, outer channel connects the lagoon to the Bay of Bengal, near the village Motto. More recently a new mouth has been opened by CDA which has brought a new lease of life to the lagoon.
Microalgae, marine seaweeds, sea grasses, fishes and crabs also flourish in the brackish water of the Chilika Lagoon.",
			},
          new Entities.specialplacesCollectionSchema
            {
                Id= new Guid("cf165b6f-f983-4321-8c77-6fb8b0c6b61a"),
                Title=@"Golden Beach at Puri",
                Subtitle=@"Puri Beach is located at the city of Puri and the distance between Puri railway station and the beach is only 2 km. Nearest airport is located at Bhubaneswar which is 60 km away. Buses and Taxis are available for local transportation.",
                Image=@"\Images\Item-8e025827-1268-46cb-8d60-6c97926d71e2.jpg",
                Description=@"Puri Beach is a beach in the city of Puri in the state of Odisha, India. It is on the shore of the Bay of Bengal. It is known for being a tourist attraction and a Hindu sacred place. The beach is the site of the annual Puri Beach Festival, which is co-sponsored by the Indian Ministry of Tourism, the city of Odisha, the Development Commissioner of Handicrafts, and the Eastern Zonal Cultural Center, Kolkata. The beach hosts sand art displays, including work by international award winning local sand artist Sudarshan Pattnaik.",
			},
          new Entities.specialplacesCollectionSchema
            {
                Id= new Guid("036ac665-a8aa-4ba6-9faa-29245bc0ca7e"),
                Title=@"Pipli",
                Subtitle=@"Pipili is on the way from Puri to Bhubaneswar. It is a small village.",
                Image=@"\Images\Item-20f210fb-5980-40eb-b4c1-a6f33c5a4202.JPG",
                Description=@"Pipili is on the way from Puri to Bhubaneswar. It is a small village. On the main road at Pipili there are many shops selling Applique work products, tourist visiting Puri buy these products from Pipili. It is famous in Orissa as well as in India for it""s applique craft. Applique, a French term, is a technique by which various cutting pieces of coloured fabrics are applied to the surface of another foundation fabric. Applique works of Pipili is also known as patching cloth design and in local language this handicraft is known as ""Chandua"".",
			},
          new Entities.specialplacesCollectionSchema
            {
                Id= new Guid("0d6113bc-39e2-4b39-b8a7-6d42924d2ccf"),
                Title=@"Puri Konark Marine Drive",
                Subtitle=@"An awesome place to have fun.",
                Image=@"\Images\Item-1e1406bb-c993-47d6-9b0c-7571513fad74.jpg",
                Description=@"This road was recently renovated and hence is in superb condition. Is peppered with deserted beaches and many rivers fall into the sea in places visible, if not accessible, from the road. Some beaches are said to have quicksands. Along the way there is a temple Ramchandi which is a popular picnic spot amongst the locals as non-veg is allowed in the temple.",
			},
		};
	
		
        /// <summary>
        /// Retrieves the data from a static data source, in an observable collection of specialplacesCollectionSchema items.
        /// </summary>
        /// <returns>An observable collection of specialplacesCollectionSchema items.</returns>
        public ObservableCollection<Entities.specialplacesCollectionSchema> GetData(int numPage)
        {								
			return new ObservableCollection<Entities.specialplacesCollectionSchema>(_data.Skip(MaxResults * numPage).Take(MaxResults));
        }
		
		/// <summary>
        /// Retrieves the data from a static data source, filtered by a filter specification, in an observable collection of specialplacesCollectionSchema items.
        /// </summary>
		/// <param name="filter">Filter operation specification</param>
        /// <returns>An observable collection of specialplacesCollectionSchema items.</returns>
        public ObservableCollection<Entities.specialplacesCollectionSchema> Search(FilterSpecification filter)
        {
            return RepositoriesBase.Filter<Entities.specialplacesCollectionSchema>.FilterCollection(filter, _data);
        }
		
		/// <summary>
        /// Checks if data source has a element before the passed as parameter
        /// </summary>
		/// <param name="current">Current element</param>
        /// <returns>True, if there is a previous element, false if there is not</returns>
		public bool HasPrevious(Entities.specialplacesCollectionSchema current)
        {
            if (current == null || !_data.Any()) return false;

            return _data.IndexOf(current) > 0;
        }
		
		/// <summary>
        /// Checks if data source has a element after the passed as parameter
        /// </summary>
		/// <param name="current">Current element</param>
        /// <returns>True, if there is a next element, false if there is not</returns>
		public bool HasNext(Entities.specialplacesCollectionSchema current)
        {
            if (current == null || !_data.Any()) return false;

            return _data.IndexOf(current) < _data.Count - 1;
        }
		
		/// <summary>
        /// Retrieves the previous element from source.
        /// </summary>
		/// <param name="current">Current element</param>
        /// <returns>The previous element from items, if it exists. Otherwise, returns null</returns>
        public Entities.specialplacesCollectionSchema Previous(Entities.specialplacesCollectionSchema current)
        {
            if (current == null || !_data.Any()) return null;

            if (_data.First().Equals(current)) return null;

            return _data[_data.IndexOf(current) - 1];
        }
		
		/// <summary>
        /// Retrieves the next element from source.
        /// </summary>
		/// <param name="current">Current element</param>
        /// <returns>The next element from items, if it exists. Otherwise, returns null</returns>
        public Entities.specialplacesCollectionSchema Next(Entities.specialplacesCollectionSchema current)
        {
            if (current == null || !_data.Any()) return null;

            if (_data.Last().Equals(current)) return null;

            return _data[_data.IndexOf(current) + 1];
        }
	}
}

